-- MySQL Script generated by MySQL Workbench
-- 03/09/20 04:59:06
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
SET sql_mode = '';

-- VAI APAGAR O BANCO DE DADOS E TODAS AS ENTRADAS -- 
-- VAI APAGAR O BANCO DE DADOS E TODAS AS ENTRADAS -- 
-- VAI APAGAR O BANCO DE DADOS E TODAS AS ENTRADAS -- 
-- VAI APAGAR O BANCO DE DADOS E TODAS AS ENTRADAS -- 
DROP SCHEMA IF EXISTS `loc`;


-- -----------------------------------------------------
-- Schema loc
-- -----------------------------------------------------
CREATE SCHEMA `loc` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `loc` ;

-- -----------------------------------------------------
-- Table `pets`
-- -----------------------------------------------------
CREATE TABLE `pets` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `alert_type` VARCHAR(10) NOT NULL,
  `species` VARCHAR(10) NOT NULL,
  `breed` VARCHAR(45) NOT NULL,
  `primary_color` VARCHAR(15) NOT NULL,
  `secondary_color` VARCHAR(15) NULL DEFAULT NULL,
  `sex` VARCHAR(10) NOT NULL,
  `coat` VARCHAR(5) NOT NULL,
  `size` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `age` VARCHAR(45) NULL DEFAULT NULL,
  `description` VARCHAR(400) NULL DEFAULT NULL,
  `avaliable_adoption` BINARY(1) DEFAULT 0,
  `user_id` INT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_pets_user_id` (`user_id`),
  CONSTRAINT `fk_pets_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `pet_pics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pet_pics` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `link_pic` VARCHAR(45) NOT NULL,
  `position_pic` INT UNSIGNED NOT NULL,
  `pet_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_pet_pics_pet_id` (`pet_id`),
  CONSTRAINT `fk_pet_pics_pet_id`
    FOREIGN KEY (`pet_id`)
    REFERENCES `pets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
  `id` INT UNSIGNED  NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL UNIQUE,
  `email` VARCHAR(45) NOT NULL UNIQUE,
  `pic_profile` VARCHAR(45) NULL,
  `password` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`)
  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alerts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alerts` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `alert_type` VARCHAR(10) NOT NULL,
  `event_date` TIMESTAMP NOT NULL,
  `id_match` INT UNSIGNED NULL DEFAULT NULL,
  `alert_ended_match` BINARY(1) NOT NULL DEFAULT 0,
  `alert_ended_delete` BINARY(1) NOT NULL DEFAULT 0,
  `ended_at` TIMESTAMP NULL DEFAULT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `pet_id` INT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_alerts_user_id` (`user_id`),
  KEY `fk_alerts_pet_id` (`pet_id`),
  CONSTRAINT `fk_alerts_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alerts_pet_id`
    FOREIGN KEY (`pet_id`)
    REFERENCES `pets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `geoloc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `geoloc` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `latitude` FLOAT NOT NULL,
  `longitude` FLOAT NOT NULL,
  `alert_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_geoloc_alert_id` (`alert_id`),
  KEY `fk_geoloc_user_id` (`user_id`),
  CONSTRAINT `fk_geoloc_alert_id`
    FOREIGN KEY (`alert_id`)
    REFERENCES `alerts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_geoloc_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comments` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `comments` VARCHAR(200) NOT NULL,
  `alert_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_comments_alert_id` (`alert_id`),
  KEY `fk_comments_user_id` (`user_id`),
  CONSTRAINT `fk_comments_alert_id`
    FOREIGN KEY (`alert_id`)
    REFERENCES `alerts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chats` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `alert_id` INT UNSIGNED NOT NULL,
  `ended_at` TIMESTAMP NULL DEFAULT NULL,
  `primary_user_id` INT UNSIGNED NOT NULL,
  `secondary_user_id` INT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_chats_user1_id` (`primary_user_id`),
  KEY `fk_chats_user2_id` (`secondary_user_id`),
  CONSTRAINT `fk_chats_user1_id`
    FOREIGN KEY (`primary_user_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chats_user2_id`
    FOREIGN KEY (`secondary_user_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `messages` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `message` VARCHAR(200) NOT NULL,
  `send_at` TIMESTAMP NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `chat_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_messages_user_id` (`user_id`),
  KEY `fk_messages_chat_id` (`chat_id`),
  CONSTRAINT `fk_messages_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_messages_chat_id`
    FOREIGN KEY (`chat_id`)
    REFERENCES `chats` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;